version: '3'

services:
  consumer:
    container_name: poc-kafka-consumer
    image: poc-kafka-consumer
    build: .
    environment:
        KAFKA_BROKER: 0.0.0.0:9092
    ports:
      - "5000:5000"
    network_mode: "host"